export const Actions ={
  //loading state
  FETCH_START:'FETCH_START',
  FETCH_END:'FETCH_END',
  GET_PRODUCT:"GET_PRODUCT",
  GET_PRODUCT_SUCCESS:"GET_PRODUCT_SUCCESS",
  //BRAND ACTIONS
  GET_BRAND:'GET_BRAND',
  GET_BRAND_SUCCESS:"GET_BRAND_SUCCESS",
  ADD_BRAND:"ADD_BRAND",
  ADD_BRAND_SUCCESS:"ADD_BRAND_SUCCESS",
  DELETE_BRAND:"DELETE_BRAND",
  DELETE_BRAND_SUCCESS:"DELETE_BRAND_SUCCESS"
}
