export const Actions ={
  //loading state
  ADD_INGREDIENTS:'ADD_INGREDIENTS',
  ADD_INGREDIENTS_SUCCESS:'ADD_INGREDIENTS_SUCCESS',
  // 对分类的操作
  GET_CATEGORY:'GET_CATEGORY',
  GET_CATEGORY_SUCCESS:'GET_CATEGORY_SUCCESS',
  ADD_CATEGORY:'ADD_CATEGORY',
  ADD_CATEGORY_SUCCESS:"ADD_CATEGORY_SUCCESS",
  DELETE_CATEGORY:'DELETE_CATEGORY',
  DELETE_CATEGORY_SUCCESS:'DELETE_CATEGORY_SUCCESS'
}
