export const Actions = {
  LOGIN:'LOGIN',
  LOGIN_SUCCESS:'LOGIN_SUCCESS',
  GET_ALL_ADMIN:'GET_ALL_ADMIN',
  GET_ALL_ADMIN_SUCCESS:'GET_ALL_ADMIN_SUCCESS',
  ADD_ADMIN:'ADD_ADMIN',
  ADD_ADMIN_SUCCESS:'ADD_ADMIN_SUCCESS',
  DELETE_ADMIN:'DELETE_ADMIN',
  DELETE_ADMIN_SUCCESS:'DELETE_ADMIN_SUCCESS'
}
