export const Actions = {
  ADD_THEORY:'ADD_THEORY',
  ADD_THEORY_SUCCESS:'ADD_THEORY_SUCCESS',
  GET_THEORY:'GET_THEORY',
  GET_THEORY_SUCCESS:'GET_THEORY_SUCCESS',
  GET_SEARCH_THEORY:'GET_SEARCH_THEORY',
  GET_SEARCH_THEORY_SUCCESS:'GET_SEARCH_THEORY_SUCCESS',
  GET_SPECIAL_THEORY:'GET_SPECIAL_THEORY',
  GET_SPECIAL_THEORY_SUCCESS:'GET_SPECIAL_THEORY_SUCCESS',
  EDIT_THEORY:'EDIT_THEORY',
  EDIT_THEORY_SUCCESS:'EDIT_THEORY_SUCCESS',
  DELETE_THEORY:'DELETE_THEORY',
  DELETE_THEORY_SUCCESS:'DELETE_THEORY_SUCCESS'
}
